name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
          ]
        include:
          - perl: 5.38
            coverage_test: true
            external_test: true
          - perl: 5.36
            external_test: true

    name: Perl ${{ matrix.perl }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install dependencies
        run: |
          cpm install -g --with-all

      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-recommends .

      - name: Install modules for external tests
        if: ${{ matrix.external_test }}
        run: |
          cpm install -g Data::Validator
          cpm install -g Exporter
          cpm install -g Exporter::Tiny
          cpm install -g Function::Parameters
          cpm install -g Moo
          cpm install -g Moose
          cpm install -g Mouse
          cpm install -g Smart::Args::TypeTiny

      - name: Build
        run: |
          perl Build.PL
          ./Build

      - name: Run test
        run: |
          ./Build test

      - name: Run coverage
        if: ${{ matrix.coverage_test }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpm install -g Devel::Cover::Report::Coveralls
          cover -test -report coveralls

